version: "2"

services:
    mha_share:
        image: debian:jessie
        volumes:
            - "./demo_share/:/mha_share/"

    mha_node:
        build: ./mha_node
        image: mha/mha_node
        read_only: true

    mha_manager:
        build: ./mha_manager
        image: mha/mha_manager
        read_only: true

    master:
        image: mha/mha_node
        depends_on:
            - mha_node
        ports:
            - "3406:3306"
        volumes:
            - "./demo_db/:/docker-entrypoint-initdb.d/:ro"
            - "./demo_master/lib/:/var/lib/mysql/"
            - "./demo_master/log/:/var/log/mysql/"
            - "./demo_master/conf.d/:/etc/mysql/mysql.conf.d/"
        volumes_from:
            - mha_share
        env_file:
            - ./.env
        environment:
            - MYSQL_USER=mha
            - MYSQL_PASSWORD=123123

    slave_1:
        image: mha/mha_node
        depends_on:
            - master
        ports:
            - "3407:3306"
        volumes:
            - "./demo_slave_1/lib/:/var/lib/mysql/"
            - "./demo_slave_1/log/:/var/log/mysql/"
            - "./demo_slave_1/conf.d/:/etc/mysql/mysql.conf.d/"
        volumes_from:
            - mha_share
        env_file:
            - ./.env
    manager:
        image: mha/mha_manager
        depends_on:
            - mha_manager
            - slave_1
        volumes_from:
            - mha_share
        entrypoint:
            tailf /dev/null
        env_file:
            - ./.env
